name    'fewbytes/zookeeper'
version '0.1.0'
source 'UNKNOWN'
author 'fewbytes'
license 'Apache License, Version 2.0'
summary 'Installs and configures apache zookeeper'
description 'UNKNOWN'
project_page 'https://github.com/fewbytes-puppet-show/fewbytes-zookeeper'

dependency 'fewbytes/upstart', '>= 0.1.0'
dependency 'gini/archive', '>= 0.1.0'
